type PhonemeInfo = { label: string; example: string };
type ExampleWord = { word: string; phonemes: string[] };

export const PHONEME_INFO: Record<string, PhonemeInfo | undefined> = {
  p:  { label: "P",  example: "pat" },
  t:  { label: "T",  example: "top" },
  k:  { label: "K",  example: "cat" },
  b:  { label: "B",  example: "bat" },
  d:  { label: "D",  example: "dog" },
  g:  { label: "G",  example: "go" },
  n:  { label: "N",  example: "net" },
  m:  { label: "M",  example: "mat" },
  ŋ:  { label: "NG", example: "ring" },
  f:  { label: "F",  example: "fan" },
  s:  { label: "S",  example: "sun" },
  θ:  { label: "TH", example: "thin" },
  ʃ:  { label: "SH", example: "ship" },
  v:  { label: "V",  example: "van" },
  z:  { label: "Z",  example: "zip" },
  ð:  { label: "TH", example: "then" },
  ʒ:  { label: "ZH", example: "measure" },
  l:  { label: "L",  example: "log" },
  ɹ:  { label: "R",  example: "ring" },
  w:  { label: "W",  example: "win" },
  j:  { label: "Y",  example: "yes" },
  h:  { label: "H",  example: "hat" },
  tʃ: { label: "CH", example: "chin" },
  dʒ: { label: "J",  example: "jam" },

  "iː": { label: "EE", example: "see" },
  ɪ:    { label: "I",  example: "bid" },
  e:    { label: "E",  example: "bed" },
  "eː": { label: "AIR", example: "hair" },
  æ:    { label: "A",  example: "bad" },
  ɐ:    { label: "U",  example: "bud" },
  "ɐː": { label: "AR", example: "bark" },
  "ɜː": { label: "ER", example: "bird" },
  "ʉː": { label: "OO", example: "boot" },
  ɔ:    { label: "O",  example: "stop" },
  "oː": { label: "OR", example: "fork" },
  ʊ:    { label: "OO", example: "book" },
  æɪ:   { label: "AY", example: "bait" },
  ɑe:   { label: "Y",  example: "bike" },
  oɪ:   { label: "OY", example: "boil" },
  əʉ:   { label: "OH", example: "boat" },
  æɔ:   { label: "OW", example: "cloud" },
  ɪə:   { label: "EAR", example: "beard" },
  ə:    { label: "UH", example: "sofa" },
};

export const PHONEME_KEYBOARD: (string | null)[][] = [
  ["p", "t", "k", null],
  ["b", "d", "g", null],
  ["n", "m", "ŋ", null],
  ["f", "s", "θ", "ʃ"],
  ["v", "z", "ð", "ʒ"],
  ["l", "ɹ", "w", "j"],
  ["h", "tʃ", "dʒ", null],
  ["iː", "ɪ", "e", "eː"],
  ["æ", "ɐ", "ɐː", "ɜː"],
  ["ʉː", "ɔ", "oː", "ʊ"],
  ["æɪ", "ɑe", "oɪ", "əʉ"],
  ["æɔ", "ɪə", null, "ə"],
];

export const WORD_LISTS: Record<number, ExampleWord[]> = {
  3: [
    { word: "bed", phonemes: ["b", "e", "d"] },
    { word: "bid", phonemes: ["b", "ɪ", "d"] },
    { word: "bad", phonemes: ["b", "æ", "d"] },
    { word: "bud", phonemes: ["b", "ɐ", "d"] },
    { word: "bird", phonemes: ["b", "ɜː", "d"] },
    { word: "bark", phonemes: ["b", "ɐː", "k"] },
    { word: "book", phonemes: ["b", "ʊ", "k"] },
    { word: "boot", phonemes: ["b", "ʉː", "t"] },
    { word: "boat", phonemes: ["b", "əʉ", "t"] },
    { word: "bike", phonemes: ["b", "ɑe", "k"] },
    { word: "bait", phonemes: ["b", "æɪ", "t"] },
    { word: "boil", phonemes: ["b", "oɪ", "l"] },
    { word: "beard", phonemes: ["b", "ɪə", "d"] },
    { word: "choice", phonemes: ["tʃ", "oɪ", "s"] },
    { word: "thin", phonemes: ["θ", "ɪ", "n"] },
    { word: "then", phonemes: ["ð", "e", "n"] },
    { word: "ship", phonemes: ["ʃ", "ɪ", "p"] },
    { word: "chin", phonemes: ["tʃ", "ɪ", "n"] },
    { word: "jam", phonemes: ["dʒ", "æ", "m"] },
    { word: "yes", phonemes: ["j", "e", "s"] },
    { word: "win", phonemes: ["w", "ɪ", "n"] },
    { word: "ring", phonemes: ["ɹ", "ɪ", "ŋ"] },
    { word: "log", phonemes: ["l", "ɔ", "g"] },
    { word: "fan", phonemes: ["f", "æ", "n"] },
    { word: "van", phonemes: ["v", "æ", "n"] },
    { word: "sun", phonemes: ["s", "ɐ", "n"] },
    { word: "zip", phonemes: ["z", "ɪ", "p"] },
    { word: "gum", phonemes: ["g", "ɐ", "m"] },
    { word: "hat", phonemes: ["h", "æ", "t"] },
    { word: "fork", phonemes: ["f", "oː", "k"] },
  ],
  4: [
    { word: "stop", phonemes: ["s", "t", "ɔ", "p"] },
    { word: "frog", phonemes: ["f", "ɹ", "ɔ", "g"] },
    { word: "clap", phonemes: ["k", "l", "æ", "p"] },
    { word: "slip", phonemes: ["s", "l", "ɪ", "p"] },
    { word: "drum", phonemes: ["d", "ɹ", "ɐ", "m"] },
    { word: "grin", phonemes: ["g", "ɹ", "ɪ", "n"] },
    { word: "train", phonemes: ["t", "ɹ", "æɪ", "n"] },
    { word: "cloud", phonemes: ["k", "l", "æɔ", "d"] },
    { word: "snake", phonemes: ["s", "n", "æɪ", "k"] },
    { word: "smile", phonemes: ["s", "m", "ɑe", "l"] },
    { word: "milk", phonemes: ["m", "ɪ", "l", "k"] },
    { word: "hand", phonemes: ["h", "æ", "n", "d"] },
    { word: "tent", phonemes: ["t", "e", "n", "t"] },
    { word: "jump", phonemes: ["dʒ", "ɐ", "m", "p"] },
    { word: "lamp", phonemes: ["l", "æ", "m", "p"] },
    { word: "bank", phonemes: ["b", "æ", "ŋ", "k"] },
    { word: "frame", phonemes: ["f", "ɹ", "æɪ", "m"] },
    { word: "cold", phonemes: ["k", "əʉ", "l", "d"] },
    { word: "wind", phonemes: ["w", "ɪ", "n", "d"] },
    { word: "soft", phonemes: ["s", "ɔ", "f", "t"] },
    { word: "gift", phonemes: ["g", "ɪ", "f", "t"] },
    { word: "desk", phonemes: ["d", "e", "s", "k"] },
    { word: "left", phonemes: ["l", "e", "f", "t"] },
    { word: "pond", phonemes: ["p", "ɔ", "n", "d"] },
    { word: "golf", phonemes: ["g", "ɔ", "l", "f"] },
    { word: "silk", phonemes: ["s", "ɪ", "l", "k"] },
    { word: "great", phonemes: ["g", "ɹ", "æɪ", "t"] },
    { word: "crab", phonemes: ["k", "ɹ", "æ", "b"] },
    { word: "plug", phonemes: ["p", "l", "ɐ", "g"] },
    { word: "quiz", phonemes: ["k", "w", "ɪ", "z"] },
  ],
  5: [
    { word: "stamp", phonemes: ["s", "t", "æ", "m", "p"] },
    { word: "plant", phonemes: ["p", "l", "æ", "n", "t"] },
    { word: "blank", phonemes: ["b", "l", "æ", "ŋ", "k"] },
    { word: "grand", phonemes: ["g", "ɹ", "æ", "n", "d"] },
    { word: "clamp", phonemes: ["k", "l", "æ", "m", "p"] },
    { word: "twist", phonemes: ["t", "w", "ɪ", "s", "t"] },
    { word: "trust", phonemes: ["t", "ɹ", "ɐ", "s", "t"] },
    { word: "drink", phonemes: ["d", "ɹ", "ɪ", "ŋ", "k"] },
    { word: "brisk", phonemes: ["b", "ɹ", "ɪ", "s", "k"] },
    { word: "shrimp", phonemes: ["ʃ", "ɹ", "ɪ", "m", "p"] },
    { word: "scrap", phonemes: ["s", "k", "ɹ", "æ", "p"] },
    { word: "scribe", phonemes: ["s", "k", "ɹ", "ɑe", "b"] },
    { word: "scream", phonemes: ["s", "k", "ɹ", "iː", "m"] },
    { word: "splash", phonemes: ["s", "p", "l", "æ", "ʃ"] },
    { word: "spring", phonemes: ["s", "p", "ɹ", "ɪ", "ŋ"] },
    { word: "strap", phonemes: ["s", "t", "ɹ", "æ", "p"] },
    { word: "street", phonemes: ["s", "t", "ɹ", "iː", "t"] },
    { word: "scrub", phonemes: ["s", "k", "ɹ", "ɐ", "b"] },
    { word: "flask", phonemes: ["f", "l", "ɐː", "s", "k"] },
    { word: "clasp", phonemes: ["k", "l", "ɐː", "s", "p"] },
    { word: "cleft", phonemes: ["k", "l", "e", "f", "t"] },
    { word: "glint", phonemes: ["g", "l", "ɪ", "n", "t"] },
    { word: "blend", phonemes: ["b", "l", "e", "n", "d"] },
    { word: "strain", phonemes: ["s", "t", "ɹ", "æɪ", "n"] },
    { word: "thrust", phonemes: ["θ", "ɹ", "ɐ", "s", "t"] },
    { word: "sprawl", phonemes: ["s", "p", "ɹ", "oː", "l"] },
    { word: "scrawl", phonemes: ["s", "k", "ɹ", "oː", "l"] },
    { word: "sprig", phonemes: ["s", "p", "ɹ", "ɪ", "g"] },
    { word: "sprout", phonemes: ["s", "p", "ɹ", "æɔ", "t"] },
    { word: "smoked", phonemes: ["s", "m", "əʉ", "k", "t"] },
  ],
};

export function getRandomWord(phonemeCount: number = 3): ExampleWord {
  const list = WORD_LISTS[phonemeCount] || WORD_LISTS[3];
  return list[Math.floor(Math.random() * list.length)];
}
